# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrE9-zvQ0vCn9nAq6eqC4f8XBKbqkWu6
"""

# Intro to Python
#Week1
# 311246169 Noa Beiman
import pandas as pd
data = {"subject_number":[1,2,3,4,5,6], "age":[15,16,17,18,19,20], "gender":["m","f","m","f","m","f"], "depression":[1,0,1,0,1,0]}
df = pd.DataFrame(data)
df.to_csv("data.csv")